package com.example.demo.dao;

import com.example.demo.dataobject.ItemstockDO;

public interface ItemstockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    int insert(ItemstockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    int insertSelective(ItemstockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    ItemstockDO selectByPrimaryKey(Integer id);
    
    //通过商品id来获得库存
    ItemstockDO selectByItemid(Integer itemid);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    int updateByPrimaryKeySelective(ItemstockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Jan 30 14:45:24 CST 2019
     */
    int updateByPrimaryKey(ItemstockDO record);
}