package com.example.demo.dataobject;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.uesr_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private Integer uesrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_price
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private Double itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderAmount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    private Double orderamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.uesr_id
     *
     * @return the value of order_info.uesr_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public Integer getUesrId() {
        return uesrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.uesr_id
     *
     * @param uesrId the value for order_info.uesr_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setUesrId(Integer uesrId) {
        this.uesrId = uesrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_id
     *
     * @return the value of order_info.item_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_id
     *
     * @param itemId the value for order_info.item_id
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_price
     *
     * @return the value of order_info.item_price
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_price
     *
     * @param itemPrice the value for order_info.item_price
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount
     *
     * @return the value of order_info.amount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount
     *
     * @param amount the value for order_info.amount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderAmount
     *
     * @return the value of order_info.orderAmount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public Double getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderAmount
     *
     * @param orderamount the value for order_info.orderAmount
     *
     * @mbg.generated Thu Jan 31 17:11:05 CST 2019
     */
    public void setOrderamount(Double orderamount) {
        this.orderamount = orderamount;
    }
}